version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379
    networks:
      - app-tier
    volumes:
      - github-repo-redis:/data

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    networks:
      - app-tier
    platform: linux/amd64
    volumes:
      - sqlite:/database


networks:
  app-tier:
    driver: bridge

volumes:
  github-repo-redis:
  sqlite:
